# inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false
Layout/LineLength:
  Max: 1000
Metrics/ClassLength:
  Max: 130
Metrics/MethodLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 60
Metrics/BlockLength:
  Max: 80
Metrics/PerceivedComplexity:
  Max: 200
Metrics/ParameterLists:
  Max: 20

AllCops:
  SuggestExtensions: false  
  Exclude:
    - 'test/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'clock.rb'
    - 'app/jobs/application_job.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'app/views/examples/**/*'
    - 'app/models/example*'
  NewCops: enable
 
